---
name: CGI-Minimal
version: 1.17
author:
  - Benjamin Franz <snowhare@nihongo.org>
abstract: A lightweight CGI form processing package
license: perl
requires:
  Module::Build: 0
  Test::More: 0.54
provides:
  CGI::Minimal:
    file: lib/CGI/Minimal.pm
    version: 1.17
generated_by: Module::Build version 0.261
